In [32]:
"""
Problem

Given a matrix of M x N elements, return all elements of
the matrix in diagonal order.

Input:
[
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
]

Output: [1, 2, 4, 7, 5, 3, 6, 8, 9]

"""
# (0, 0) (0, 1), (1, 0), (2, 0), (1, 1), (0, 2), (1, 2), (2, 1), (2, 2)

import functools
import operator
import numpy as np


def diagonal_traverse(matrix):

    rows, cols = matrix.shape
    result = []
    direction = np.array([-1, 1])
    r, c = (0, 0)
    
    for _ in range(rows + cols - 1):
        while 0 <= r < rows and 0 <= c < cols:
            result.append(matrix[r][c])
            r += direction[0]
            c += direction[1]
        direction = -direction

        # Case 1 (left side) -> down
        if c == -1 and r != rows:
            c = 0
        
        # Case 2 (top side) -> right
        elif r == -1 and c != cols:
            r = 0
        
        # Case 3 (bottom side) -> right
        elif r == rows and c != cols:
            r -= 1
            c += 2
        
        # Case 4 (right side) -> down
        elif c == cols and r != rows:
            c -= 1
            r += 2
        
        # Case 5 (top right corner)
        elif r == -1 and c == cols:
            r = 1
            c -= 1
        
        # Case 6 (bottom left corner)
        elif r == rows and c == -1:
            c = 1
            r -= 1
        
        else:
            raise ValueError
    
    return result


def test_diagonal_traverse():
    
    shapes = [(1, 1), (2, 2), (3, 3), (4, 4), (2, 4),
              (3, 4), (2, 6), (3, 6), (4, 6), (5, 6)]
    shapes.extend([tuple(reversed(s)) for s in shapes])
    shapes = sorted(list(set(shapes)))
    
    for shape in shapes:
        ran = functools.reduce(operator.mul, shape)
        matrix = np.arange(ran).reshape(shape)
        print('>>> matrix{0}'.format(shape))
        print(matrix, '\n')
        print('>>> diagonal_traverse(matrix)')
        print(diagonal_traverse(matrix))
        print('\n-----------------------------------\n')

        
test_diagonal_traverse()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
>>> matrix(1, 1)
[[0]] 

>>> diagonal_traverse(matrix)
[0]

-----------------------------------

>>> matrix(2, 2)
[[0 1]
 [2 3]] 

>>> diagonal_traverse(matrix)
[0, 1, 2, 3]

-----------------------------------

>>> matrix(2, 4)
[[0 1 2 3]
 [4 5 6 7]] 

>>> diagonal_traverse(matrix)
[0, 1, 4, 5, 2, 3, 6, 7]

-----------------------------------

>>> matrix(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

>>> diagonal_traverse(matrix)
[0, 1, 6, 7, 2, 3, 8, 9, 4, 5, 10, 11]

-----------------------------------

>>> matrix(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

>>> diagonal_traverse(matrix)
[0, 1, 3, 6, 4, 2, 5, 7, 8]

-----------------------------------

>>> matrix(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

>>> diagonal_traverse(matrix)
[0, 1, 4, 8, 5, 2, 3, 6, 9, 10, 7, 11]

-----------------------------------

>>> matrix(3, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

>>> diagonal_traverse(matrix)
[0, 1, 6, 12, 7, 2, 3, 8, 13