<h2><center>Power Set</center></h2>
<h3>Problem:</h3>
<p>
    The input for this problem will be an array of numbers representing a set, which only contains unique numbers,<br>
    and your goal is to print every possible set combination, otherwise known as the power set.
</p>
<p>
    <strong>For example:</strong><br>
    input set = [1, 2, 3]<br>
    power set = [[], [1], [2], [3], [1, 2], [2, 3], [1, 3] [1, 2, 3]]<br>
</p>
<p>
The power set contains every possible combination of numbers. It also includes the empty set which contains no numbers from the original set.
</p>

In [33]:
import numpy as np
import random


def power_set(nums):
    N = 2 ** len(nums)
    result = []
    
    for i in range(N):
        subset = []
        for j in range(len(nums)):
            if (1 << j) & i:
                subset.append(nums[j])
        result.append(subset)
    return result


def power_set_numpy(nums):
    assert(nums.ndim == 1)
    N = 2 ** nums.size
    mask = np.zeros_like(nums, dtype=np.bool)
    result = []
    zero = np.array([False])
    for i in range(N):
        mask &= zero
        for j in range(nums.size):
            if 1 << j & i:
                mask[j] = True
        result.append(nums[mask])
    return result


power_set([1, 2, 3, 4])
power_set_numpy(np.array([1, 2, 3, 4]))

[array([], dtype=int32),
 array([1]),
 array([2]),
 array([1, 2]),
 array([3]),
 array([1, 3]),
 array([2, 3]),
 array([1, 2, 3]),
 array([4]),
 array([1, 4]),
 array([2, 4]),
 array([1, 2, 4]),
 array([3, 4]),
 array([1, 3, 4]),
 array([2, 3, 4]),
 array([1, 2, 3, 4])]

In [31]:
%timeit power_set(list(range(10)))

1.96 ms ± 115 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
%timeit power_set_numpy(np.arange(10))

3.67 ms ± 331 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
